config/routes.rb
Votinbox::Application.routes.draw do

  root :to => 'index#index'
  
  get 'board', :controller => "users"

  get 'cmusummit2012', :controller => "events", :action => "show"
  

end

app/models/event.rb
class Event

  include Mongoid::Document
  field :name
  field :shorturl
  belongs_to :user
  embeds_many :votes
  
  validates_presence_of :name
  validates_length_of :name, :maximum => 255

  validates_presence_of :shorturl

end

app/models/user.rb
class User

  include Mongoid::Document
  field :username
  field :hashed_password
  field :salt
  has_many :events, :uniq => true
  has_many :votes, :uniq => true
  
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_format_of :name, :with => /^[a-zA-Z\d_]*$/
  validates_length_of :name, :maximum => 15
  
  validates_confirmation_of :password
  validates_confirmation_of :password
  validates_presence_of :password_confirmation, :if => :hashed_password_changed?
  validates_length_of :password, :in => 6..64, :if => :hashed_password_changed?
  
  attr_accessible :name, :password, :password_confirmation
  attr_accessor :password
  
  def self.authenticate(name, password)
    user = self.find_by_name(name)
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.hashed_password != expected_password
        user = nil
      end
    end
    user
  end

  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = self.class.encrypted_password(self.password, self.salt)
  end

  def add_invitations(copy=12)
    (1..copy).to_a.each do
      Invitation.create(
        :code => Invitation.generate_code,
        :user_id => id
      )
    end
  end

private

  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end

  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end

end

app/models/vote.rb
class Vote

  include Mongoid::Document
  field :name
  has_many :judges, :through => :judges, :source => :user, :uniq => true
  embeds_in :votes
  belongs_to :user
  
  validates_presence_of :name
  validates_length_of :name, :maximum => 255

  validates_presence_of :shorturl

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def board
    session[:user_id] = 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_thumbnail.html.erb
<% if event == 'new' %>

<div class="thumbnail">
	<%= image_tag("placehold-it.gif")%>
	<div class="caption">
		<a href="#" class="btn btn-mini btn-primary pull-right disabled">Create New</a>
		<h5>To be avaiable</h5>
	</div>
</div>

<% else %>

<div class="thumbnail">
	<%= image_tag("cmu.jpg")%>
	<div class="caption">
		<a href="/cmusummit2012" class="btn btn-mini btn-success pull-right">Vote</a>
		<a href="/cmusummit2012" class="btn btn-mini btn-danger pull-right">Edit</a>
		<a href="/cmusummit2012" class="btn btn-mini btn-primary pull-right">Enter</a>
		<h5>CMU Summit New Venture Competition, 2012</h5>
	</div>
</div>

<% end %>

app/views/index/_login.html.erb
<div class="modal hide" id="modal-login">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Login</h3>
	</div>
	<div class="modal-body">
		<form class="form-horizontal">
			<fieldset>
				<div class="control-group">
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-user"></i></span><input class="span2" type="text" placeholder="Username"/>
						</div>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-lock"></i></span><input class="span2" type="password" placeholder="Password"/>
						</div>	
					</div>	
				</div>
			</fieldset>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-primary">Login</a>
	</div>
</div>

app/views/index/_signup.html.erb
<div class="modal hide" id="modal-signup">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Sign up</h3>
	</div>
	<div class="modal-body">
		<form class="form-horizontal">
			<fieldset>
				<div class="control-group">
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-user"></i></span><input class="span2" type="text" placeholder="Username"/>
						</div>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-lock"></i></span><input class="span2" type="password" placeholder="Password"/>
						</div>	
					</div>	
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-lock"></i></span><input class="span2" type="password" placeholder="Confirm"/>
						</div>	
					</div>	
				</div>
				
			</fieldset>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-primary">Sign up</a>
	</div>
</div>

app/views/index/index.html.erb
<div id="spotlight">
	<div class="row-fluid">
		<div class="span12">
			<h1>Instant Audience Feedback</h1>
			<h2>The readily available fail-safe live voting services with all features customizable.</h2>
			<div class="row-fluid">
				<div id="left-spot" class="span5">
					<ul id="spotlight-features">
						<li>
							<h3>Improve audience involvement</h3>
							<p>Large-scale audience participation feature.</p>
						</li>
						<li>
							<h3>Set up in seconds</h3>
							<p>Fast launch of new events.</p>
						</li>
						<li>
							<h3>Free trials for everything</h3>
							<p>Premier experience prior to purchasing our services.</p>
						</li>
					</ul>
					<%= link_to "signup" do %>
					<a class="btn-larger btn btn-primary" data-toggle="modal" href="#modal-signup" >Get started now</a>
					<% end %>
				</div>
				<div id="right-spot" class="span7">
					<div id="slide-wrapper">
						<div id="slides" class="thumbnail">
							<%= image_tag("placehold-it.gif")%>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="event-review">
	<div class="row-fluid">
		<div class="span12">
			<div class="row-fluid">
				<div id="current-event" class="span6">
					<h3>Current Event</h3>
					<%= render :partial => "events/thumbnail", :locals => { :event => 'cmu' } %>
				</div>
				<div id="previous-event" class="span6">
					<h3>Previous Events</h3>
					<div class="carousel thumbnail">
						<!-- Carousel items -->
						<div class="carousel-inner">
							<div class="item active">
								<%= image_tag("harvard.jpg")%>
								<div class="caption">
									<h5>Zhenfund Harvard, 2011</h5>
								</div>
							</div>
							<div class="item">
								<%= image_tag("mit.jpg")%>
								<div class="caption">
									<h5>MITCHIEF, 2011</h5>
								</div>
							</div>
							<div class="item">
								<%= image_tag("iweekend.jpg")%>
								<div class="caption">
									<h5>iWeekend, 2011</h5>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="vote-review">
	<div class="row-fluid">
		<div class="span12">
			<h3>Stream</h3>
		</div>
	</div>
</div>

<%= render :partial => 'index/signup' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	<title>Votinbox</title>
	<meta name="description" content="Votin’ Box is a pioneer solution to the lack of live online voting systems for educational organizations.">
	<meta name="author" content="Unit Interval Studio">
	<meta name="viewport" content="width=device-width">
	<%= stylesheet_link_tag "application", :media => "all" %>
	
	<%= csrf_meta_tags %>
</head>
<body>
	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href="/">Votinbox</a>
				<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<div class="nav-collapse">
					<ul class="nav pull-right">
						<% if session[:user_id] %>
						<li><%= link_to "Dashboard", board_path %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">cmusummit<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<a data-toggle="modal" href="#modal-account" >Account Setting</a>
								</li>
								<li>
									<%= link_to "Sign out", "logout"%>
								</li>
							</ul>
						</li>
						<% else %>
						<li>
							<a data-toggle="modal" href="#modal-login" >Login</a>
						</li>
						<% end %>							
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>
	
	<%= render :partial => 'index/login' %>

	<div class="container-fluid">
		<% if flash[:notice] %>
		<div class="row-fluid">
			<div class="span12">
				<div class="alert">
					<a class="close" data-dismiss="alert">×</a>
					<strong>Notice!</strong> <%= flash[:notice] %>
				</div>
			</div>
		</div>
		<% end %>

		<%= yield %>

		<div class="footer">
			<div class="row-fluid">
				<div class="span12">
					<p class="pull-right"><a href="#">Back to top</a></p>
					<p>Copyright 2012 Unit Interval Studio</p>
				</div>
			</div>
		</div>

	</div> <!-- /container -->

	<!-- Le javascript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<%= javascript_include_tag "application" %>

</body>
</html>

app/views/users/_account.html.erb
<div class="modal hide" id="modal-account">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Account Setting</h3>
	</div>
	<div class="modal-body">
		<form class="form-horizontal">
			<fieldset>
				<div class="control-group">
					<h4>Update username:</h4>
					<div class="controls">
						<div class="input-prepend input-append">
							<span class="add-on"><i class="icon-user"></i></span><input class="span2" type="text" placeholder="Username"/><button class="btn" type="button">Save</button>
						</div>
					</div>
				</div>
				<div class="control-group">
					<h4>Change password:</h4>
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-lock"></i></span><input class="span2" type="password" placeholder="Old password"/>
						</div>	
					</div>	
					<div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-lock"></i></span><input class="span2" type="password" placeholder="New password"/>
						</div>	
					</div>	
					<div class="controls">
						<div class="input-prepend input-append">
							<span class="add-on"><i class="icon-lock"></i></span><input class="span2" type="password" placeholder="Confirm"/><button class="btn" type="button">Update</button>
						</div>	
					</div>	
				</div>
			</fieldset>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>

app/views/users/board.html.erb
<div id="board">
	<div class="row-fluid">
		<div class="span6">
			<%= render :partial => 'events/thumbnail', :locals => { :event => 'new' } %>
		</div>
		<div class="span6">
			<%= render :partial => 'events/thumbnail', :locals => { :event => 'cmu' } %>
		</div>
	</div>
</div>

<%= render :partial => 'users/account' %>